spring.application.name=Artico

### Database
#spring.datasource.url=jdbc:postgresql://localhost:5432/artico_db
spring.datasource.url=jdbc:postgresql://localhost:5432/test1
spring.datasource.username=postgres
spring.datasource.password=admin

### Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

### JWT
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.access-token-expiration=10m
security.jwt.refresh-token-expiration=30d

### Request Mapping
app.request-mapping.auth=/api/auth

### Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

