spring.application.name=Artico

### Database
#spring.datasource.url=jdbc:postgresql://localhost:5432/artico_db
spring.datasource.url=jdbc:postgresql://localhost:5432/test1
spring.datasource.username=postgres
spring.datasource.password=admin

### Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
